trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepo: 'javapp'
  dockerfilePath: 'app/Dockerfile'
  imageTag: $(Build.BuildId)
  acr-service-connection: 'acr-devops-connection'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image

    jobs:
      - job: DockerBuildandPush
        displayName: Build and Push Docker Image

        steps:
          - checkout: self
          - task: Docker@2
            displayName: Docker Build and Push
            inputs:
             containerRegistry: $(acr-service-connection)
             repository: '$(imageRepo)'
             command: 'buildAndPush'
             Dockerfile: '$(dockerfilePath)'
             tags: |
               latest
               $(imageTag)