trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: 'javapp'
  dockerfilePath: 'app/Dockerfile'
  imageTag: $(Build.BuildId)
  acr-server-connection: 'acr-devops-challenge'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image

    jobs:
      - job: DockerBuildandPush
        displayName: Build and Push Docker Image

        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and Push Docker Image 
            inputs:
              containerRegistry: $(acr-server-connection)
              repository: '$(imageRepository)'
              command: 'build'
              Dockerfile: $(dockerfilePath)
              tags: |
                latest
                $(imageTag)
 