apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: devops-task

spec:
  provider: azure

  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: DB-PASSWORD
          key: DB_PASSWORD

        - objectName: DB-USERNAME
          key: DB_USERNAME

        - objectName: DB-NAME
          key: DB_NAME

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "425e61ec-236c-4f0c-b65f-69911c790846"

    keyvaultName: "devops-aks-kv-saikiran1"
    tenantId: "3194f2f0-fb80-43d6-af7e-db489787113a"

    objects: |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret

        - |
          objectName: DB-USERNAME
          objectType: secret

        - |
          objectName: DB-NAME
          objectType: secret